apiVersion: apps/v1
kind: Deployment
metadata:
  name: axis-backend
  namespace: skala3-finalproj-class3-team13
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-creds
      containers:
        - name: api          # base 의 container name 과 일치 (backend X)
          imagePullPolicy: Always           # arch 변경 시 cache mismatch 방지
