apiVersion: v1
kind: Service
metadata:
  name: axis-backend
  namespace: axis
  labels:
    app: axis-backend
    tier: business
spec:
  type: ClusterIP
  selector:
    app: axis-backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
