apiVersion: v1
kind: Service
metadata:
  name: demo-newsroom
  namespace: skala3-finalproj-class3-team13
  labels:
    app: demo-newsroom
    tier: presentation
spec:
  type: ClusterIP
  selector:
    app: demo-newsroom
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
