apiVersion: v1
kind: Service
metadata:
  name: axis-frontend
  namespace: skala3-finalproj-class3-team13
  labels:
    app: axis-frontend
    tier: presentation
spec:
  type: ClusterIP
  selector:
    app: axis-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
